In [1]:
# ==========================================
# 1. SETUP & IMPORTS
# ==========================================
from pyspark.sql import SparkSession, functions as F
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler, StandardScaler, StringIndexer, OneHotEncoder
from pyspark.ml.regression import GBTRegressor, RandomForestRegressor, GeneralizedLinearRegression
import os

# Initialize Spark
spark = (SparkSession.builder
    .appName("BIXI-Model-Factory")
    .config("spark.sql.session.timeZone", "America/Toronto")
    .getOrCreate())

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/04/17 23:22:08 WARN Utils: Your hostname, Comanes-MacBook-Pro.local, resolves to a loopback address: 127.0.0.1; using 192.168.0.11 instead (on interface en0)
26/04/17 23:22:08 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/17 23:22:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [ ]:
# ==========================================
# 2. CONFIGURATION (Change this for new stations)
# ==========================================
targetStation = "STN_0001"
gold_path = "data/gold/station_flow"
models_save_dir = f"models/{targetStation}/"

# Ensure save directory exists
os.makedirs(models_save_dir, exist_ok=True)

In [ ]:
# ==========================================
# 3. DATA LOADING & TEMPORAL SPLIT
# ==========================================
print(f"Loading data for {targetStation}...")
gold_df = spark.read.parquet(gold_path).filter(F.col("station_id") == targetStation)

# Hardcoded temporal split based on business requirements
split_date = "2025-08-01 00:00:00"

# For the factory, we ONLY need the training data (< 2025-08-01)
train_df = gold_df.filter(F.col("ts_hour") < split_date).cache()
print(f"Training Data Ready: {train_df.count():,} rows. Cutoff date: strictly before {split_date}")

Loading data for STN_0004...

26/04/17 23:22:11 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

Training Data Ready: 19,304 rows. Cutoff date: strictly before 2025-08-01 00:00:00

In [4]:
# ==========================================
# 4. FEATURE DEFINITIONS
# ==========================================
EXCLUDE_COLS = ["ts_hour", "station_id", "station_inflow", "station_outflow", "station_netflow"]

# Define numeric and categorical columns
categorical_cols = ["temp_bin"] # Add any other string columns here
numeric_cols = [f.name for f in train_df.schema.fields 
                if f.dataType.typeName() in ['integer', 'long', 'double', 'float'] 
                and f.name not in EXCLUDE_COLS]

# Create standard feature stages
feature_stages = []
for col in categorical_cols:
    feature_stages.append(StringIndexer(inputCol=col, outputCol=f"{col}_idx", handleInvalid="keep"))
    feature_stages.append(OneHotEncoder(inputCol=f"{col}_idx", outputCol=f"{col}_vec"))

encoded_cols = [f"{col}_vec" for col in categorical_cols]
assembler = VectorAssembler(inputCols=numeric_cols + encoded_cols, outputCol="features", handleInvalid="skip")
feature_stages.append(assembler)

# Add a scaler specifically for the Poisson GLR
scaler = StandardScaler(inputCol="features", outputCol="scaledFeatures", withStd=True, withMean=False)

In [11]:
# ==========================================
# 5. MODEL ARCHITECTURES & TUNING GRIDS
# ==========================================
from pyspark.ml.regression import GBTRegressor, RandomForestRegressor, GeneralizedLinearRegression
from pyspark.ml.tuning import ParamGridBuilder

# Define the base models 
gbt = GBTRegressor(featuresCol="features", seed=42)
rf = RandomForestRegressor(featuresCol="features", seed=42)
poisson = GeneralizedLinearRegression(featuresCol="scaledFeatures", family="poisson", link="log")

# Build the grids
gbt_grid = (ParamGridBuilder()
    .addGrid(gbt.maxDepth, [4, 6])          
    .addGrid(gbt.maxIter, [50, 100])        
    .build())

rf_grid = (ParamGridBuilder()
    .addGrid(rf.maxDepth, [5, 10])      
    .addGrid(rf.numTrees, [50, 100])        
    .build())

poisson_grid = (ParamGridBuilder()
    .addGrid(poisson.regParam, [0.01, 0.1]) 
    .build())

# THE CRITICAL FIX: The nested dictionary
architectures = {
    "GBT": {"model": gbt, "grid": gbt_grid},
    "RF": {"model": rf, "grid": rf_grid},
    "Poisson": {"model": poisson, "grid": poisson_grid}
}

In [ ]:
# ==========================================
# 6. THE BASIC TRAINING LOOP
# ==========================================
for flow_type, target_col in targets.items():
    print(f"\n--- Training {flow_type.upper()} Models ---")
    
    for model_name, algo in architectures.items():
        print(f"Training {model_name}...")
        
        # Set the target column dynamically
        algo.setLabelCol(target_col)
        
        # Build Pipeline (Poisson needs the scaler)
        if model_name == "Poisson":
            pipeline = Pipeline(stages=feature_stages + [scaler, algo])
        else:
            pipeline = Pipeline(stages=feature_stages + [algo])
            
        # Fit the model
        trained_model = pipeline.fit(train_df)
        
        # Save the model to disk (overwrite if exists)
        save_path = os.path.join(models_save_dir, f"{flow_type}_{model_name}")
        trained_model.write().overwrite().save(save_path)
        print(f"✅ Saved to: {save_path}")

print("\n🎉 All models trained and saved successfully!")

--- Training OUTFLOW Models ---
Training GBT...

26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1000.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1005.5 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1008.4 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1008.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1009.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1010.6 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1012.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1017.3 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1020.4 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1020.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1021.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1022.7 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1025.0 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1029.0 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1031.6 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1032.1 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1033.1 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1033.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1036.2 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1040.8 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1043.4 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1043.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1044.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1045.6 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1047.9 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1051.7 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1054.1 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1054.6 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1055.6 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1056.4 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1058.7 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1063.0 KiB
26/04/17 23:30:39 WARN DAGScheduler: Broadcasting large task binary with size 1065.4 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1065.9 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1066.9 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1067.7 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1070.0 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1073.7 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1076.0 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1076.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1077.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1078.2 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1080.0 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1083.4 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1086.3 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1086.8 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1087.8 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1088.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1090.8 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1094.6 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1097.1 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1097.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1098.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1099.3 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1101.6 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1106.1 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1108.3 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1108.7 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1109.7 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1110.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1112.8 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1117.5 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1120.8 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1121.3 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1122.3 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1123.0 KiB
26/04/17 23:30:40 WARN DAGScheduler: Broadcasting large task binary with size 1125.3 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1128.7 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1130.9 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1131.4 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1132.4 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1133.1 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1135.4 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1139.5 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1141.8 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1142.3 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1143.3 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1144.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1146.4 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1150.7 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1153.7 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1154.2 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1155.2 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1156.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1158.2 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1161.6 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1163.5 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1164.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1165.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1165.7 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1168.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1172.4 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1175.0 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1175.5 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1176.5 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1177.3 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1179.6 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1184.1 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1186.7 KiB
26/04/17 23:30:41 WARN DAGScheduler: Broadcasting large task binary with size 1187.2 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1188.2 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1189.0 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1191.2 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1195.3 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1198.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1198.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1199.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1200.4 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1202.7 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1207.2 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1210.3 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1210.8 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1211.8 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1212.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1214.8 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1218.3 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1220.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1221.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1222.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1222.8 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1225.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1229.8 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1233.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1233.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1234.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1235.3 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1237.6 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1241.9 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1244.7 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1245.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1246.1 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1246.9 KiB
26/04/17 23:30:42 WARN DAGScheduler: Broadcasting large task binary with size 1248.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1252.6 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1255.4 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1255.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1256.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1257.6 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1260.0 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1264.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1266.6 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1267.1 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1268.1 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1268.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1271.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1275.6 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1278.7 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1279.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1280.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1280.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1283.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1287.8 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1291.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1291.7 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1292.7 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1293.5 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1295.5 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1299.1 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1300.7 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1301.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1302.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1302.9 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1305.2 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1309.5 KiB
26/04/17 23:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1312.2 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1312.7 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1313.7 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1314.5 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1316.8 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1320.7 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1323.1 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1323.6 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1324.6 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1325.4 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1327.7 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1332.3 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1335.3 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1335.8 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1336.8 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1337.6 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1339.9 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1344.5 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1347.5 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1348.0 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1349.0 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1349.7 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1352.0 KiB
26/04/17 23:30:44 WARN DAGScheduler: Broadcasting large task binary with size 1355.7 KiB

✅ Saved to: models/STN_0004/outflow_GBT
Training RF...

26/04/17 23:30:47 WARN DAGScheduler: Broadcasting large task binary with size 1431.2 KiB
26/04/17 23:30:48 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:30:49 WARN DAGScheduler: Broadcasting large task binary with size 4.8 MiB
26/04/17 23:30:50 WARN DAGScheduler: Broadcasting large task binary with size 1139.6 KiB
26/04/17 23:30:51 WARN DAGScheduler: Broadcasting large task binary with size 7.9 MiB
26/04/17 23:30:52 WARN DAGScheduler: Broadcasting large task binary with size 1770.9 KiB
26/04/17 23:30:53 WARN DAGScheduler: Broadcasting large task binary with size 8.8 MiB
26/04/17 23:30:54 WARN DAGScheduler: Broadcasting large task binary with size 1769.2 KiB
26/04/17 23:30:55 WARN DAGScheduler: Broadcasting large task binary with size 6.4 MiB
26/04/17 23:30:56 WARN DAGScheduler: Broadcasting large task binary with size 1306.6 KiB
26/04/17 23:30:56 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/17 23:30:58 WARN TaskSetManager: Stage 3872 contains a task of very large size (2661 KiB). The maximum recommended task size is 1000 KiB.

✅ Saved to: models/STN_0004/outflow_RF
Training Poisson...
✅ Saved to: models/STN_0004/outflow_Poisson

--- Training INFLOW Models ---
Training GBT...

26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1000.0 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1000.8 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1003.1 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1007.4 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1009.9 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1010.4 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1011.4 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1012.2 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1014.5 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1019.0 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1021.8 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1022.2 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1023.2 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1024.0 KiB
26/04/17 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1026.3 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1030.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1032.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1032.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1033.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1034.4 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1036.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1039.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1041.4 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1041.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1042.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1043.6 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1045.9 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1050.5 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1053.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1053.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1054.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1055.5 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1057.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1062.4 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1065.6 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1066.1 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1067.1 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1067.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1070.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1074.8 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1077.7 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1078.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1079.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1080.0 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1082.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1086.2 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1088.9 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1089.4 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1090.4 KiB
26/04/17 23:31:10 WARN DAGScheduler: Broadcasting large task binary with size 1091.2 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1093.5 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1098.1 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1101.2 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1101.6 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1102.6 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1103.4 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1105.7 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1110.0 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1112.6 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1113.0 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1114.0 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1114.8 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1117.1 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1120.8 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1123.1 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1123.6 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1124.6 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1125.3 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1127.3 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1130.8 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1132.9 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1133.4 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1134.4 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1135.2 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1137.5 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1142.1 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1145.3 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1145.8 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1146.3 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1147.2 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1148.9 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1151.4 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1153.0 KiB
26/04/17 23:31:11 WARN DAGScheduler: Broadcasting large task binary with size 1153.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1154.4 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1155.2 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1157.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1161.6 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1163.6 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1164.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1165.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1165.8 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1168.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1172.7 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1176.0 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1176.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1177.4 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1178.2 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1180.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1185.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1188.0 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1188.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1189.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1190.0 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1191.7 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1195.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1197.6 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1198.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1199.1 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1199.9 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1202.2 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1205.7 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1208.0 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1208.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1209.4 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1210.2 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1212.5 KiB
26/04/17 23:31:12 WARN DAGScheduler: Broadcasting large task binary with size 1217.1 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1220.2 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1220.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1221.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1222.5 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1224.5 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1228.6 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1231.5 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1232.0 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1233.0 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1233.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1236.0 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1240.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1243.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1244.1 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1245.1 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1245.9 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1248.2 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1252.8 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1256.2 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1256.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1257.7 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1258.5 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1260.8 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1265.4 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1268.1 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1268.6 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1269.6 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1270.4 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1272.4 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1276.4 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1279.5 KiB
26/04/17 23:31:13 WARN DAGScheduler: Broadcasting large task binary with size 1280.0 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1281.0 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1281.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1283.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1287.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1290.6 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1291.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1292.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1292.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1295.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1299.4 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1301.2 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1301.7 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1302.7 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1303.4 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1305.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1308.3 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1310.6 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1311.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1312.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1312.9 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1315.2 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1319.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1322.6 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1323.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1324.0 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1324.8 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1327.1 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1331.4 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1333.9 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1334.4 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1335.4 KiB
26/04/17 23:31:14 WARN DAGScheduler: Broadcasting large task binary with size 1336.2 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1338.5 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1342.7 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1345.2 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1345.7 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1346.7 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1347.4 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1349.7 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1354.0 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1357.1 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1357.6 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1358.5 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1359.3 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1361.3 KiB
26/04/17 23:31:15 WARN DAGScheduler: Broadcasting large task binary with size 1364.7 KiB

✅ Saved to: models/STN_0004/inflow_GBT
Training RF...

26/04/17 23:31:18 WARN DAGScheduler: Broadcasting large task binary with size 1431.7 KiB
26/04/17 23:31:19 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:31:20 WARN DAGScheduler: Broadcasting large task binary with size 4.9 MiB
26/04/17 23:31:21 WARN DAGScheduler: Broadcasting large task binary with size 1154.7 KiB
26/04/17 23:31:22 WARN DAGScheduler: Broadcasting large task binary with size 7.8 MiB
26/04/17 23:31:23 WARN DAGScheduler: Broadcasting large task binary with size 1770.7 KiB
26/04/17 23:31:24 WARN DAGScheduler: Broadcasting large task binary with size 8.7 MiB
26/04/17 23:31:25 WARN DAGScheduler: Broadcasting large task binary with size 1769.3 KiB
26/04/17 23:31:26 WARN DAGScheduler: Broadcasting large task binary with size 6.7 MiB
26/04/17 23:31:26 WARN DAGScheduler: Broadcasting large task binary with size 1388.1 KiB
26/04/17 23:31:27 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/04/17 23:31:28 WARN TaskSetManager: Stage 5168 contains a task of very large size (2723 KiB). The maximum recommended task size is 1000 KiB.

✅ Saved to: models/STN_0004/inflow_RF
Training Poisson...
✅ Saved to: models/STN_0004/inflow_Poisson

🎉 All models trained and saved successfully!

In [12]:
# ==========================================
# 7. TIME-SERIES HYPERPARAMETER TUNING 
# ==========================================

from pyspark.ml.evaluation import RegressionEvaluator

# We split the training data AGAIN to create a strict "Validation" period
# Example: Let's use the month of July 2025 as the tuning validation set
validation_date = "2025-07-01 00:00:00"

# Train the tuning models on everything before July
tune_train_df = train_df.filter(F.col("ts_hour") < validation_date).cache()
# Evaluate the tuning models strictly on July
tune_val_df = train_df.filter(F.col("ts_hour") >= validation_date).cache()

print(f"Tuning Train Size: {tune_train_df.count():,} | Tuning Val Size (July): {tune_val_df.count():,}")

evaluator = RegressionEvaluator(metricName="rmse")

for flow_type, target_col in targets.items():
    print(f"\n--- Tuning {flow_type.upper()} Models ---")
    evaluator.setLabelCol(target_col)
    
    for model_name, components in architectures.items():
        print(f"Starting Time-Series Grid Search for {model_name}...")
        
        algo = components["model"]
        grid = components["grid"]
        algo.setLabelCol(target_col)
        
        best_rmse = float("inf")
        best_params = None
        
        # Loop through every combination of parameters Spark generated
        for param_map in grid:
            # Apply the parameters to the algorithm
            algo_with_params = algo.copy(param_map)
            
            # Build temporary pipeline
            if model_name == "Poisson":
                pipeline = Pipeline(stages=feature_stages + [scaler, algo_with_params])
            else:
                pipeline = Pipeline(stages=feature_stages + [algo_with_params])
            
            # Train on the past (< July)
            temp_model = pipeline.fit(tune_train_df)
            
            # Predict on the future (July)
            predictions = temp_model.transform(tune_val_df)
            current_rmse = evaluator.evaluate(predictions)
            
            # Keep track of the lowest error
            if current_rmse < best_rmse:
                best_rmse = current_rmse
                best_params = param_map
                
        print(f"🏆 Best {model_name} Params found! RMSE: {best_rmse:.3f}")
        
        # FINAL STEP: Retrain the absolute best model on the FULL training set (< August)
        print(f"Retraining final {model_name} on all training data...")
        final_algo = algo.copy(best_params)
        final_pipeline = Pipeline(stages=feature_stages + ([scaler, final_algo] if model_name == "Poisson" else [final_algo]))
        
        best_final_model = final_pipeline.fit(train_df)
        
        # Save to disk
        save_path = os.path.join(models_save_dir, f"{flow_type}_{model_name}_optimized")
        best_final_model.write().overwrite().save(save_path)
        print(f"✅ Saved to: {save_path}")

26/04/17 23:33:32 WARN CacheManager: Asked to cache already cached data.
26/04/17 23:33:32 WARN CacheManager: Asked to cache already cached data.

Tuning Train Size: 18,560 | Tuning Val Size (July): 744

--- Tuning OUTFLOW Models ---
Starting Time-Series Grid Search for GBT...

26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1000.0 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1004.0 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1006.4 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1006.8 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1007.8 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1008.6 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1010.9 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1014.6 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1016.8 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1017.2 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1018.2 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1019.0 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1021.3 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1025.3 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1028.0 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1028.5 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1029.5 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1030.2 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1032.3 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1036.2 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1038.9 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1039.3 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1039.9 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1040.8 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1042.5 KiB
26/04/17 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 1045.7 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1048.0 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1048.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1049.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1050.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1052.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1055.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1057.4 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1057.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1058.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1059.7 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1062.0 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1066.6 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1069.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1069.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1070.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1071.7 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1074.0 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1078.6 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1081.7 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1082.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1083.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1083.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1086.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1090.9 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1094.0 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1094.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1095.5 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1096.3 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1098.6 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1103.1 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1106.2 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1106.7 KiB
26/04/17 23:34:10 WARN DAGScheduler: Broadcasting large task binary with size 1107.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1108.4 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1110.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1115.1 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1117.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1118.2 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1119.2 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1120.0 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1122.3 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1127.0 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1130.2 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1130.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1131.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1132.4 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1134.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1138.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1141.4 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1141.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1142.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1143.6 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1145.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1149.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1152.3 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1152.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1153.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1154.5 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1156.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1161.4 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1164.4 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1164.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1165.9 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1166.7 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1169.0 KiB
26/04/17 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 1173.3 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1176.1 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1176.6 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1177.6 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1178.4 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1180.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1184.9 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1187.5 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1188.0 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1189.0 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1189.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1192.1 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1196.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1199.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1200.2 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1201.2 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1202.0 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1204.3 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1208.8 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1211.4 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1211.9 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1212.9 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1213.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1215.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1219.5 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1221.7 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1222.2 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1223.2 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1224.0 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1226.3 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1230.3 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1232.8 KiB
26/04/17 23:34:12 WARN DAGScheduler: Broadcasting large task binary with size 1233.3 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1234.3 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1235.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1237.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1240.8 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1243.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1243.6 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1244.6 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1245.3 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1247.6 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1251.9 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1254.6 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1255.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1256.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1256.8 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1258.5 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1262.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1264.5 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1265.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1266.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1266.8 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1269.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1273.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1275.7 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1276.2 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1277.2 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1278.0 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1280.3 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1284.6 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1287.1 KiB
26/04/17 23:34:13 WARN DAGScheduler: Broadcasting large task binary with size 1287.6 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1288.6 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1289.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1291.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1295.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1297.7 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1298.2 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1299.2 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1299.9 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1302.2 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1306.3 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1308.9 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1309.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1310.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1311.1 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1313.5 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1317.7 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1320.5 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1320.9 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1321.9 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1322.7 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1324.7 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1328.7 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1331.6 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1332.1 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1333.1 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1333.8 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1336.1 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1340.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1343.0 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1343.4 KiB
26/04/17 23:34:14 WARN DAGScheduler: Broadcasting large task binary with size 1344.4 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1345.2 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1347.5 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1352.1 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1355.3 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1355.8 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1356.8 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1357.5 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1359.8 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1363.9 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1366.2 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1366.7 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1367.7 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1368.4 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1370.5 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1374.2 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1376.3 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1376.7 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1377.7 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1378.5 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1380.5 KiB
26/04/17 23:34:15 WARN DAGScheduler: Broadcasting large task binary with size 1384.6 KiB

🏆 Best GBT Params found! RMSE: 6.060
Retraining final GBT on all training data...
✅ Saved to: models/STN_0004/outflow_GBT_optimized
Starting Time-Series Grid Search for RF...

26/04/17 23:34:33 WARN DAGScheduler: Broadcasting large task binary with size 1459.3 KiB
26/04/17 23:34:34 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:34:35 WARN DAGScheduler: Broadcasting large task binary with size 4.6 MiB
26/04/17 23:34:36 WARN DAGScheduler: Broadcasting large task binary with size 7.8 MiB
26/04/17 23:34:37 WARN DAGScheduler: Broadcasting large task binary with size 1574.2 KiB
26/04/17 23:34:40 WARN DAGScheduler: Broadcasting large task binary with size 1458.6 KiB
26/04/17 23:34:41 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:34:43 WARN DAGScheduler: Broadcasting large task binary with size 4.9 MiB
26/04/17 23:34:44 WARN DAGScheduler: Broadcasting large task binary with size 1130.8 KiB
26/04/17 23:34:45 WARN DAGScheduler: Broadcasting large task binary with size 8.0 MiB
26/04/17 23:34:46 WARN DAGScheduler: Broadcasting large task binary with size 1771.0 KiB
26/04/17 23:34:47 WARN DAGScheduler: Broadcasting large task binary with size 8.9 MiB
26/04/17 23:34:48 WARN DAGScheduler: Broadcasting large task binary with size 1769.1 KiB
26/04/17 23:34:49 WARN DAGScheduler: Broadcasting large task binary with size 6.3 MiB
26/04/17 23:34:50 WARN DAGScheduler: Broadcasting large task binary with size 1266.6 KiB
26/04/17 23:34:51 WARN DAGScheduler: Broadcasting large task binary with size 2038.6 KiB

🏆 Best RF Params found! RMSE: 5.918
Retraining final RF on all training data...

26/04/17 23:34:54 WARN DAGScheduler: Broadcasting large task binary with size 1431.2 KiB
26/04/17 23:34:55 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:34:56 WARN DAGScheduler: Broadcasting large task binary with size 4.8 MiB
26/04/17 23:34:57 WARN DAGScheduler: Broadcasting large task binary with size 1139.6 KiB
26/04/17 23:34:58 WARN DAGScheduler: Broadcasting large task binary with size 7.9 MiB
26/04/17 23:34:59 WARN DAGScheduler: Broadcasting large task binary with size 1770.9 KiB
26/04/17 23:35:00 WARN DAGScheduler: Broadcasting large task binary with size 8.8 MiB
26/04/17 23:35:01 WARN DAGScheduler: Broadcasting large task binary with size 1769.2 KiB
26/04/17 23:35:02 WARN DAGScheduler: Broadcasting large task binary with size 6.4 MiB
26/04/17 23:35:03 WARN DAGScheduler: Broadcasting large task binary with size 1306.6 KiB
26/04/17 23:35:03 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/17 23:35:05 WARN TaskSetManager: Stage 9234 contains a task of very large size (2661 KiB). The maximum recommended task size is 1000 KiB.

✅ Saved to: models/STN_0004/outflow_RF_optimized
Starting Time-Series Grid Search for Poisson...
🏆 Best Poisson Params found! RMSE: 10.681
Retraining final Poisson on all training data...
✅ Saved to: models/STN_0004/outflow_Poisson_optimized

--- Tuning INFLOW Models ---
Starting Time-Series Grid Search for GBT...

26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1000.9 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1001.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1002.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1003.1 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1005.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1009.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1011.7 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1012.2 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1013.2 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1013.9 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1016.2 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1020.9 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1023.9 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1024.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1025.4 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1026.2 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1028.5 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1032.7 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1035.3 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1035.8 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1036.8 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1037.5 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1039.5 KiB
26/04/17 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1043.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1046.7 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1047.2 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1048.2 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1048.9 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1051.0 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1054.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1057.0 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1057.4 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1058.0 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1058.9 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1060.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1062.9 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1065.1 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1065.5 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1066.5 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1067.3 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1069.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1074.2 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1077.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1078.1 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1079.1 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1079.8 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1082.1 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1086.4 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1089.4 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1089.9 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1090.9 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1091.7 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1094.0 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1098.6 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1101.8 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1102.3 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1103.3 KiB
26/04/17 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1104.0 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1106.3 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1110.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1113.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1114.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1115.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1115.9 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1118.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1122.3 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1124.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1125.1 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1126.1 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1126.9 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1129.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1133.8 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1137.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1137.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1138.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1139.4 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1141.7 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1146.3 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1148.9 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1149.4 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1150.4 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1151.2 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1153.5 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1157.6 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1160.5 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1161.0 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1162.0 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1162.8 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1165.0 KiB
26/04/17 23:35:45 WARN DAGScheduler: Broadcasting large task binary with size 1169.4 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1172.2 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1172.7 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1173.7 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1174.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1176.8 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1181.0 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1183.8 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1184.3 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1185.3 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1186.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1188.4 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1193.0 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1196.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1196.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1197.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1198.3 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1200.6 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1204.9 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1207.8 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1208.3 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1209.3 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1210.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1212.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1216.2 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1219.0 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1219.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1220.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1221.2 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1223.5 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1228.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1231.1 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1231.6 KiB
26/04/17 23:35:46 WARN DAGScheduler: Broadcasting large task binary with size 1232.1 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1233.0 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1234.7 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1236.7 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1238.8 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1239.2 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1240.2 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1241.0 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1243.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1247.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1249.8 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1250.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1251.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1252.1 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1254.4 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1258.9 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1261.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1261.8 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1262.8 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1263.6 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1265.9 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1270.2 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1272.9 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1273.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1274.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1275.1 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1277.4 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1281.3 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1283.6 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1284.1 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1285.1 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1285.8 KiB
26/04/17 23:35:47 WARN DAGScheduler: Broadcasting large task binary with size 1287.9 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1291.6 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1294.2 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1294.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1295.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1296.4 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1298.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1302.4 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1304.8 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1305.3 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1306.3 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1307.0 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1309.3 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1313.2 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1315.2 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1315.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1316.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1317.5 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1319.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1323.7 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1326.0 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1326.4 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1327.4 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1328.2 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1330.6 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1335.2 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1338.4 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1338.8 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1339.8 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1340.6 KiB
26/04/17 23:35:48 WARN DAGScheduler: Broadcasting large task binary with size 1342.9 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1347.5 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1350.7 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1351.2 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1352.2 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1353.0 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1355.2 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1359.0 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1361.6 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1362.1 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1363.1 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1363.8 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1366.1 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1370.8 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1374.1 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1374.6 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1375.6 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1376.3 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1378.6 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1383.2 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1386.0 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1386.4 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1387.4 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1388.2 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1390.5 KiB
26/04/17 23:35:49 WARN DAGScheduler: Broadcasting large task binary with size 1394.2 KiB

🏆 Best GBT Params found! RMSE: 4.441
Retraining final GBT on all training data...
✅ Saved to: models/STN_0004/inflow_GBT_optimized
Starting Time-Series Grid Search for RF...

26/04/17 23:36:05 WARN DAGScheduler: Broadcasting large task binary with size 1463.4 KiB
26/04/17 23:36:06 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:36:07 WARN DAGScheduler: Broadcasting large task binary with size 4.6 MiB
26/04/17 23:36:07 WARN DAGScheduler: Broadcasting large task binary with size 1019.4 KiB
26/04/17 23:36:08 WARN DAGScheduler: Broadcasting large task binary with size 8.1 MiB
26/04/17 23:36:09 WARN DAGScheduler: Broadcasting large task binary with size 1645.8 KiB
26/04/17 23:36:12 WARN DAGScheduler: Broadcasting large task binary with size 1458.2 KiB
26/04/17 23:36:13 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:36:14 WARN DAGScheduler: Broadcasting large task binary with size 4.9 MiB
26/04/17 23:36:15 WARN DAGScheduler: Broadcasting large task binary with size 1158.2 KiB
26/04/17 23:36:16 WARN DAGScheduler: Broadcasting large task binary with size 7.9 MiB
26/04/17 23:36:17 WARN DAGScheduler: Broadcasting large task binary with size 1770.6 KiB
26/04/17 23:36:18 WARN DAGScheduler: Broadcasting large task binary with size 8.7 MiB
26/04/17 23:36:19 WARN DAGScheduler: Broadcasting large task binary with size 1769.4 KiB
26/04/17 23:36:20 WARN DAGScheduler: Broadcasting large task binary with size 6.7 MiB
26/04/17 23:36:21 WARN DAGScheduler: Broadcasting large task binary with size 1364.5 KiB
26/04/17 23:36:21 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB

🏆 Best RF Params found! RMSE: 4.418
Retraining final RF on all training data...

26/04/17 23:36:24 WARN DAGScheduler: Broadcasting large task binary with size 1432.4 KiB
26/04/17 23:36:24 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/04/17 23:36:25 WARN DAGScheduler: Broadcasting large task binary with size 4.6 MiB
26/04/17 23:36:26 WARN DAGScheduler: Broadcasting large task binary with size 1029.5 KiB
26/04/17 23:36:27 WARN DAGScheduler: Broadcasting large task binary with size 8.1 MiB
26/04/17 23:36:28 WARN DAGScheduler: Broadcasting large task binary with size 1671.1 KiB
26/04/17 23:36:29 WARN TaskSetManager: Stage 13112 contains a task of very large size (1370 KiB). The maximum recommended task size is 1000 KiB.

✅ Saved to: models/STN_0004/inflow_RF_optimized
Starting Time-Series Grid Search for Poisson...
🏆 Best Poisson Params found! RMSE: 8.073
Retraining final Poisson on all training data...
✅ Saved to: models/STN_0004/inflow_Poisson_optimized

In [ ]:
#########
# COMPARISON TABLE OF ALL MODELS
#########

import pandas as pd
import os
from pyspark.ml import PipelineModel
from pyspark.ml.evaluation import RegressionEvaluator

# 1. Setup our three mathematical evaluators
rmse_evaluator = RegressionEvaluator(metricName="rmse")
mae_evaluator = RegressionEvaluator(metricName="mae")
r2_evaluator = RegressionEvaluator(metricName="r2")

# Create an empty list to hold our results
evaluation_results = []

print("Evaluating saved models... This might take a moment.")

# 2. Loop through both Inflow and Outflow
for flow_type, target_col in targets.items():
    
    # Tell the evaluators which column represents the "Truth"
    rmse_evaluator.setLabelCol(target_col)
    mae_evaluator.setLabelCol(target_col)
    r2_evaluator.setLabelCol(target_col)
    
    # 3. Loop through the three architectures we trained
    for model_name in ["GBT", "RF", "Poisson"]:
        
        # Construct the path to where the model is saved
        model_path = os.path.join(models_save_dir, f"{flow_type}_{model_name}_optimized")
        
        try:
            # Load the optimized pipeline from disk
            loaded_model = PipelineModel.load(model_path)
            
            # Make predictions on your validation/test set 
            # Note: Replace 'tune_val_df' with whatever dataframe you want to test on!
            predictions = loaded_model.transform(tune_val_df)
            
            # Calculate the metrics
            rmse = rmse_evaluator.evaluate(predictions)
            mae = mae_evaluator.evaluate(predictions)
            r2 = r2_evaluator.evaluate(predictions)
            
            # Store the results
            evaluation_results.append({
                "Flow Type": flow_type.upper(),
                "Model": model_name,
                "RMSE": round(rmse, 3),
                "MAE": round(mae, 3),
                "R-Squared": round(r2, 3)
            })
            
        except Exception as e:
            print(f"Could not evaluate {flow_type} {model_name}. Did it save correctly? Error: {e}")

# 4. Convert the results into a clean Pandas DataFrame for visualization
comparison_df = pd.DataFrame(evaluation_results)

# Sort the table so it's easy to read: Group by Flow Type, then rank by best MAE
comparison_df = comparison_df.sort_values(by=["Flow Type", "MAE"], ascending=[True, True]).reset_index(drop=True)

print("\n🏆 Model Comparison Table 🏆")
display(comparison_df) # Use print(comparison_df) if 'display' doesn't work in your environment

Evaluating saved models... This might take a moment.

🏆 Model Comparison Table 🏆

  Flow Type    Model    RMSE    MAE  R-Squared
0    INFLOW      GBT   3.225  2.430      0.900
1    INFLOW       RF   3.459  2.603      0.885
2    INFLOW  Poisson   7.765  5.318      0.419
3   OUTFLOW       RF   4.368  3.286      0.899
4   OUTFLOW      GBT   4.808  3.585      0.878
5   OUTFLOW  Poisson  10.223  7.020      0.446

# outflow model (RF) optimisation

In [ ]:
#########
# FEATURE IMPORTANCE ANALYSIS (For the best RF model)
#########

import pandas as pd
from pyspark.ml import PipelineModel

import pandas as pd
from pyspark.ml import PipelineModel

# 1. Load the model
model_path = f"models/{targetStation}/outflow_RF_optimized"
print(f"Loading model from: {model_path}...")
loaded_pipeline = PipelineModel.load(model_path)
ml_model = loaded_pipeline.stages[-1]

# 2. Extract the importances array
importances = ml_model.featureImportances.toArray()

# 3. THE FIX: Extract true feature names from PySpark metadata
# We push 1 row of data through the pipeline to generate the metadata
# Note: Using 'tune_val_df' here, but you can use 'train_df' or any df in memory
sample_transformed = loaded_pipeline.transform(tune_val_df.limit(1))

# Get the exact column the model used (usually "features")
features_col_name = ml_model.getFeaturesCol()

# Dig into PySpark's hidden metadata dictionary
feature_attrs = sample_transformed.schema[features_col_name].metadata["ml_attr"]["attrs"]

# Unpack the metadata into a list of (index, name) tuples
extracted_names = []
for attr_group in feature_attrs.values():
    for attr in attr_group:
        extracted_names.append((attr['idx'], attr['name']))

# Sort strictly by index so it matches the importances array perfectly!
extracted_names.sort(key=lambda x: x[0])
true_feature_names = [name for idx, name in extracted_names]

# 4. Build a clean Pandas DataFrame (Now they will be the exact same length!)
importance_df = pd.DataFrame({
    "Feature": true_feature_names,
    "Importance": importances
})

# 5. Calculate the percentage and display
importance_df["Importance_%"] = (importance_df["Importance"] * 100).round(2)
importance_df = importance_df.sort_values(by="Importance", ascending=False).reset_index(drop=True)

print("\n🏆 Top 10 Most Important Features:")
display(importance_df.head(10))

print("\n🗑️ The 'Noise' (Bottom 15 Features):")
display(importance_df.tail(15))

In [ ]:
# Extract the top 15 feature names from your ranked dataframe
top_15_features = importance_df["Feature"].head(15).tolist()

print("🎯 Your Top 15 Winning Features:")
print("TOP_15_COLS =", top_15_features)

In [29]:
# ==========================================
# STRICT FEATURE DEFINITIONS (Pruned to Top 15)
# ==========================================

# Paste the list you generated in Step 1 right here:
TOP_15_COLS = [
    "radius200m_outflow_lag1" , 
    "radius200m_inflow_lag1" , 
    "radius100m_inflow_lag1", 
    "station_inflow_lag1" , 
    "hod_cos" , 
    "radius500m_outflow_lag1", 
    "hod" , 
    "radius500m_inflow_lag1", 
    "radius100m_outflow_rollmean6", 
    "radius100m_outflow_lag1", 
    "station_outflow_rollmean6" , 
    "radius100m_inflow_rollmean6" , 
    "radius100m_outflow_rollmean12" , 
    "station_outflow_rollsum6" , 
    "radius200m_outflow_rollmean6" 
]

# Create standard feature stages
feature_stages = []

# NOTE: If any of your categorical columns made the Top 15, 
# you still need to StringIndex and OneHotEncode them here!
categorical_cols = ["temp_bin"] # Keep this if temp_bin is in your Top 15

for col in categorical_cols:
    feature_stages.append(StringIndexer(inputCol=col, outputCol=f"{col}_idx", handleInvalid="keep"))
    feature_stages.append(OneHotEncoder(inputCol=f"{col}_idx", outputCol=f"{col}_vec"))

# Build the final VectorAssembler strictly from your top 15 list
assembler = VectorAssembler(inputCols=TOP_15_COLS, outputCol="features", handleInvalid="skip")
feature_stages.append(assembler)

# Add the scaler for the Poisson GLR
scaler = StandardScaler(inputCol="features", outputCol="scaledFeatures", withStd=True, withMean=False)

In [30]:
# ==========================================
# 1. SETUP & STRICT TEMPORAL SPLITS
# ==========================================
import os
import pyspark.sql.functions as F
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.tuning import ParamGridBuilder
from pyspark.ml.evaluation import RegressionEvaluator

targetStation = "STN_0004" # Change if testing a different station
target_col = "station_outflow"

# Ensure gold_df is loaded beforehand, then filter to the target station
gold_df_stn = gold_df.filter(F.col("station_id") == targetStation)

# Time bounds (Train < Aug 1st, Test >= Aug 1st)
test_date = "2025-08-01 00:00:00"
validation_date = "2025-07-01 00:00:00" # Carving out July for tuning

# Create splits
train_full_df = gold_df_stn.filter(F.col("ts_hour") < test_date).cache()
test_df = gold_df_stn.filter(F.col("ts_hour") >= test_date).cache()

# Splitting train further for tuning
tune_train_df = train_full_df.filter(F.col("ts_hour") < validation_date).cache()
tune_val_df = train_full_df.filter(F.col("ts_hour") >= validation_date).cache()

print(f"Data Ready!")
print(f"Total Training Pool (< Aug): {train_full_df.count():,} rows")
print(f"Testing Data (>= Aug): {test_df.count():,} rows")

# ==========================================
# 2. STRICT TOP 15 FEATURES
# ==========================================
TOP_15_COLS = [
    "radius200m_outflow_lag1", 
    "radius200m_inflow_lag1", 
    "radius100m_inflow_lag1", 
    "station_inflow_lag1", 
    "hod_cos", 
    "radius500m_outflow_lag1", 
    "hod", 
    "radius500m_inflow_lag1", 
    "radius100m_outflow_rollmean6", 
    "radius100m_outflow_lag1", 
    "station_outflow_rollmean6", 
    "radius100m_inflow_rollmean6", 
    "radius100m_outflow_rollmean12", 
    "station_outflow_rollsum6", 
    "radius200m_outflow_rollmean6" 
]

# Because all 15 are numeric, we only need the VectorAssembler!
assembler = VectorAssembler(inputCols=TOP_15_COLS, outputCol="features", handleInvalid="skip")
feature_stages = [assembler]

# ==========================================
# 3. RANDOM FOREST ARCHITECTURE & TUNING
# ==========================================
rf = RandomForestRegressor(featuresCol="features", labelCol=target_col, seed=42)

# The Grid: Test 6 combinations
rf_grid = (ParamGridBuilder()
    .addGrid(rf.maxDepth, [5, 10, 15])      
    .addGrid(rf.numTrees, [50, 100])        
    .build())

evaluator_rmse = RegressionEvaluator(labelCol=target_col, metricName="rmse")
evaluator_mae = RegressionEvaluator(labelCol=target_col, metricName="mae")

print(f"\n--- Tuning OUTFLOW Random Forest ---")
best_rmse = float("inf")
best_params = None

for param_map in rf_grid:
    rf_with_params = rf.copy(param_map)
    pipeline = Pipeline(stages=feature_stages + [rf_with_params])
    
    # Train on past (< July), evaluate on July
    temp_model = pipeline.fit(tune_train_df)
    predictions = temp_model.transform(tune_val_df)
    current_rmse = evaluator_rmse.evaluate(predictions)
    
    if current_rmse < best_rmse:
        best_rmse = current_rmse
        best_params = param_map

print(f"🏆 Best Tuning RMSE (on July Data): {best_rmse:.3f}")

# ==========================================
# 4. FINAL TRAINING & TEST SET EVALUATION
# ==========================================
print(f"\nRetraining final optimized RF on ALL training data (< August)...")
final_rf = rf.copy(best_params)
final_pipeline = Pipeline(stages=feature_stages + [final_rf])

best_final_model = final_pipeline.fit(train_full_df)

# Evaluate on the REAL Future (>= August 1st)
print(f"Testing model on unseen August+ data...")
test_predictions = best_final_model.transform(test_df)

final_rmse = evaluator_rmse.evaluate(test_predictions)
final_mae = evaluator_mae.evaluate(test_predictions)

print("\n==================================")
print("🚀 FINAL TEST SET RESULTS (OUTFLOW)")
print("==================================")
print(f"Test MAE:  {final_mae:.3f} bikes")
print(f"Test RMSE: {final_rmse:.3f} bikes")
print("==================================")

# (Optional) Save it to disk for the Netflow Evaluator later
save_path = f"models/{targetStation}/outflow_RF_optimized"
best_final_model.write().overwrite().save(save_path)

Data Ready!
Total Training Pool (< Aug): 19,304 rows
Testing Data (>= Aug): 4,417 rows

--- Tuning OUTFLOW Random Forest ---

26/04/18 00:06:23 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:06:23 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:06:23 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:06:23 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:06:26 WARN DAGScheduler: Broadcasting large task binary with size 1144.5 KiB
26/04/18 00:06:27 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/18 00:06:27 WARN DAGScheduler: Broadcasting large task binary with size 3.7 MiB
26/04/18 00:06:28 WARN DAGScheduler: Broadcasting large task binary with size 6.6 MiB
26/04/18 00:06:28 WARN DAGScheduler: Broadcasting large task binary with size 1564.0 KiB
26/04/18 00:06:30 WARN DAGScheduler: Broadcasting large task binary with size 1140.5 KiB
26/04/18 00:06:31 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/18 00:06:31 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
26/04/18 00:06:32 WARN DAGScheduler: Broadcasting large task binary with size 1122.6 KiB
26/04/18 00:06:32 WARN DAGScheduler: Broadcasting large task binary with size 7.3 MiB
26/04/18 00:06:33 WARN DAGScheduler: Broadcasting large task binary with size 1945.9 KiB
26/04/18 00:06:33 WARN DAGScheduler: Broadcasting large task binary with size 12.9 MiB
26/04/18 00:06:34 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/04/18 00:06:36 WARN DAGScheduler: Broadcasting large task binary with size 1144.5 KiB
26/04/18 00:06:36 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/18 00:06:37 WARN DAGScheduler: Broadcasting large task binary with size 3.7 MiB
26/04/18 00:06:38 WARN DAGScheduler: Broadcasting large task binary with size 6.6 MiB
26/04/18 00:06:38 WARN DAGScheduler: Broadcasting large task binary with size 1564.0 KiB
26/04/18 00:06:39 WARN DAGScheduler: Broadcasting large task binary with size 10.9 MiB
26/04/18 00:06:39 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/04/18 00:06:40 WARN DAGScheduler: Broadcasting large task binary with size 17.2 MiB
26/04/18 00:06:41 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/04/18 00:06:42 WARN DAGScheduler: Broadcasting large task binary with size 25.3 MiB
26/04/18 00:06:43 WARN DAGScheduler: Broadcasting large task binary with size 3.7 MiB
26/04/18 00:06:44 WARN DAGScheduler: Broadcasting large task binary with size 35.0 MiB
26/04/18 00:06:45 WARN DAGScheduler: Broadcasting large task binary with size 4.2 MiB
26/04/18 00:06:47 WARN DAGScheduler: Broadcasting large task binary with size 45.8 MiB
26/04/18 00:06:48 WARN DAGScheduler: Broadcasting large task binary with size 4.4 MiB
26/04/18 00:06:51 WARN DAGScheduler: Broadcasting large task binary with size 1140.5 KiB
26/04/18 00:06:52 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/04/18 00:06:52 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
26/04/18 00:06:53 WARN DAGScheduler: Broadcasting large task binary with size 1122.6 KiB
26/04/18 00:06:53 WARN DAGScheduler: Broadcasting large task binary with size 7.3 MiB
26/04/18 00:06:54 WARN DAGScheduler: Broadcasting large task binary with size 1945.9 KiB
26/04/18 00:06:55 WARN DAGScheduler: Broadcasting large task binary with size 12.9 MiB
26/04/18 00:06:56 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/04/18 00:06:57 WARN DAGScheduler: Broadcasting large task binary with size 21.6 MiB
26/04/18 00:06:58 WARN DAGScheduler: Broadcasting large task binary with size 4.5 MiB
26/04/18 00:07:00 WARN DAGScheduler: Broadcasting large task binary with size 34.1 MiB
26/04/18 00:07:02 WARN DAGScheduler: Broadcasting large task binary with size 6.0 MiB
26/04/18 00:07:05 WARN DAGScheduler: Broadcasting large task binary with size 47.2 MiB
26/04/18 00:07:08 WARN DAGScheduler: Broadcasting large task binary with size 6.8 MiB
26/04/18 00:07:11 WARN DAGScheduler: Broadcasting large task binary with size 57.7 MiB
26/04/18 00:07:13 WARN DAGScheduler: Broadcasting large task binary with size 6.8 MiB
26/04/18 00:07:17 WARN DAGScheduler: Broadcasting large task binary with size 71.7 MiB
26/04/18 00:07:19 WARN DAGScheduler: Broadcasting large task binary with size 6.8 MiB
26/04/18 00:07:21 WARN DAGScheduler: Broadcasting large task binary with size 15.5 MiB
26/04/18 00:07:22 WARN DAGScheduler: Broadcasting large task binary with size 1808.1 KiB
26/04/18 00:07:22 WARN DAGScheduler: Broadcasting large task binary with size 15.6 MiB
26/04/18 00:07:22 WARN DAGScheduler: Broadcasting large task binary with size 1516.1 KiB
26/04/18 00:07:23 WARN DAGScheduler: Broadcasting large task binary with size 6.7 MiB

🏆 Best Tuning RMSE (on July Data): 6.158

Retraining final optimized RF on ALL training data (< August)...

26/04/18 00:07:26 WARN DAGScheduler: Broadcasting large task binary with size 1113.3 KiB
26/04/18 00:07:26 WARN DAGScheduler: Broadcasting large task binary with size 2.0 MiB
26/04/18 00:07:27 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
26/04/18 00:07:28 WARN DAGScheduler: Broadcasting large task binary with size 1123.5 KiB
26/04/18 00:07:28 WARN DAGScheduler: Broadcasting large task binary with size 7.2 MiB
26/04/18 00:07:29 WARN DAGScheduler: Broadcasting large task binary with size 1953.3 KiB
26/04/18 00:07:30 WARN DAGScheduler: Broadcasting large task binary with size 12.9 MiB
26/04/18 00:07:31 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB

Testing model on unseen August+ data...

==================================
🚀 FINAL TEST SET RESULTS (OUTFLOW)
==================================
Test MAE:  3.148 bikes
Test RMSE: 4.954 bikes
==================================

26/04/18 00:07:32 WARN TaskSetManager: Stage 13765 contains a task of very large size (2602 KiB). The maximum recommended task size is 1000 KiB.

In [31]:
### adding feature interactions to try improving model ###

from featureinteractions import add_misery_index, add_temporal_context

from featureinteractions import add_misery_index, add_temporal_context
import pyspark.sql.functions as F

# 1. Apply interactions with a CAST for the boolean column
gold_df_stn = (gold_df.filter(F.col("station_id") == targetStation)
    # Misery index works fine (likely two numbers)
    .transform(lambda df: add_misery_index(df, temp_col="temp", precip_col="precip"))
    
    # THE FIX: Cast is_weekday to "int" so Spark can multiply it by the hour
    .withColumn("is_weekday", F.col("is_weekday").cast("int"))
    
    # Now the function will work perfectly!
    .transform(lambda df: add_temporal_context(df, hour_col="hod", weekend_col="is_weekday")) 
)

# 2. Add these to your potential winners
POTENTIAL_COLS = TOP_15_COLS + ["temp_precip_int", "hod_is_weekend_int"]

print("Interactions created successfully!")

# Now proceed with your splits as before
train_full_df = gold_df_stn.filter(F.col("ts_hour") < test_date).cache()
tune_train_df = train_full_df.filter(F.col("ts_hour") < validation_date).cache()
tune_val_df = train_full_df.filter(F.col("ts_hour") >= validation_date).cache()
print("Training and validation sets created successfully!")

Interactions created successfully!
Training and validation sets created successfully!

26/04/18 00:07:33 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:07:33 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:07:33 WARN CacheManager: Asked to cache already cached data.

In [32]:
import pandas as pd
from pyspark.ml import PipelineModel
from pyspark.ml.evaluation import RegressionEvaluator

# 1. SETUP - Use the exact same path where you just saved the optimized RF
targetStation = "STN_0004"
test_path = f"models/{targetStation}/outflow_RF_optimized"

# Ensure your test_df is ready (the one >= 2025-08-01)
print(f"Loading fresh model for {targetStation}...")
final_rf_model = PipelineModel.load(test_path)

# 2. GENERATE PREDICTIONS
# This uses the 15 features (including interactions) to predict the future
test_predictions = final_rf_model.transform(test_df)

# 3. CALCULATE METRICS
evaluator_rmse = RegressionEvaluator(labelCol="station_outflow", metricName="rmse")
evaluator_mae = RegressionEvaluator(labelCol="station_outflow", metricName="mae")
evaluator_r2 = RegressionEvaluator(labelCol="station_outflow", metricName="r2")

rmse = evaluator_rmse.evaluate(test_predictions)
mae = evaluator_mae.evaluate(test_predictions)
r2 = evaluator_r2.evaluate(test_predictions)

# 4. DISPLAY THE WINNING STATS
results_data = {
    "Metric": ["MAE (Mean Absolute Error)", "RMSE (Root Mean Squared Error)", "R-Squared"],
    "Value": [round(mae, 4), round(rmse, 4), round(r2, 4)]
}

results_df = pd.DataFrame(results_data)

print("\n🚀 NEWLY TRAINED MODEL RESULTS (OUTFLOW)")
print("==========================================")
display(results_df)

if mae < 2.5:
    print(f"\n✅ SUCCESS! Your MAE is {mae:.3f}. You smashed the 2.xx goal!")
else:
    print(f"\n📈 Current MAE: {mae:.3f}. We are getting closer!")

Loading fresh model for STN_0004...

🚀 NEWLY TRAINED MODEL RESULTS (OUTFLOW)
==========================================

                           Metric   Value
0       MAE (Mean Absolute Error)  3.1476
1  RMSE (Root Mean Squared Error)  4.9542
2                       R-Squared  0.8576

📈 Current MAE: 3.148. We are getting closer!

feature interactions did not better the MAE.

# Optimising best inflow model (GBT)

In [ ]:
#########
# FEATURE IMPORTANCE ANALYSIS (For the best GBT model)
#########

import pandas as pd
from pyspark.ml import PipelineModel

import pandas as pd
from pyspark.ml import PipelineModel

# 1. Load the model
model_path = f"models/{targetStation}/inflow_GBT_optimized"
print(f"Loading model from: {model_path}...")
loaded_pipeline = PipelineModel.load(model_path)
ml_model = loaded_pipeline.stages[-1]

# 2. Extract the importances array
importances = ml_model.featureImportances.toArray()

# 3. THE FIX: Extract true feature names from PySpark metadata
# We push 1 row of data through the pipeline to generate the metadata
# Note: Using 'tune_val_df' here, but you can use 'train_df' or any df in memory
sample_transformed = loaded_pipeline.transform(tune_val_df.limit(1))

# Get the exact column the model used (usually "features")
features_col_name = ml_model.getFeaturesCol()

# Dig into PySpark's hidden metadata dictionary
feature_attrs = sample_transformed.schema[features_col_name].metadata["ml_attr"]["attrs"]

# Unpack the metadata into a list of (index, name) tuples
extracted_names = []
for attr_group in feature_attrs.values():
    for attr in attr_group:
        extracted_names.append((attr['idx'], attr['name']))

# Sort strictly by index so it matches the importances array perfectly!
extracted_names.sort(key=lambda x: x[0])
true_feature_names = [name for idx, name in extracted_names]

# 4. Build a clean Pandas DataFrame (Now they will be the exact same length!)
importance_df = pd.DataFrame({
    "Feature": true_feature_names,
    "Importance": importances
})

# 5. Calculate the percentage and display
importance_df["Importance_%"] = (importance_df["Importance"] * 100).round(2)
importance_df = importance_df.sort_values(by="Importance", ascending=False).reset_index(drop=True)

print("\n🏆 Top 10 Most Important Features:")
display(importance_df.head(10))

print("\n🗑️ The 'Noise' (Bottom 15 Features):")
display(importance_df.tail(15))

Loading model from: models/STN_0004/inflow_GBT_optimized...

🏆 Top 10 Most Important Features:

                        Feature  Importance  Importance_%
0        radius200m_inflow_lag1    0.328640         32.86
1   radius100m_inflow_rollmean6    0.089254          8.93
2                           hod    0.087207          8.72
3                       hod_cos    0.049770          4.98
4        radius500m_inflow_lag1    0.042828          4.28
5  radius100m_inflow_rollmean12    0.039454          3.95
6                       dow_cos    0.029061          2.91
7        radius100m_inflow_lag1    0.025385          2.54
8       radius100m_outflow_lag1    0.024366          2.44
9       radius500m_outflow_lag1    0.023761          2.38

🗑️ The 'Noise' (Bottom 15 Features):

                         Feature  Importance  Importance_%
52  radius100m_outflow_rollsum12         0.0           0.0
53    radius200m_inflow_rollsum6         0.0           0.0
54   radius200m_outflow_rollsum6         0.0           0.0
55   radius200m_inflow_rollsum12         0.0           0.0
56  radius200m_outflow_rollsum12         0.0           0.0
57    radius500m_inflow_rollsum6         0.0           0.0
58   radius500m_inflow_rollsum12         0.0           0.0
59  radius500m_outflow_rollsum12         0.0           0.0
60           station_inflow_lag1         0.0           0.0
61          station_outflow_lag1         0.0           0.0
62          station_inflow_lag12         0.0           0.0
63         station_outflow_lag12         0.0           0.0
64      station_inflow_rollmean6         0.0           0.0
65     station_outflow_rollmean6         0.0           0.0
66             temp_bin_vec_<-20         0.0           0.0

In [34]:
# Extract the top 15 feature names from your ranked dataframe
top_15_features = importance_df["Feature"].head(15).tolist()

print("🎯 Your Top 15 Winning Features:")
print("TOP_15_COLS =", top_15_features)

🎯 Your Top 15 Winning Features:
TOP_15_COLS = ['radius200m_inflow_lag1', 'radius100m_inflow_rollmean6', 'hod', 'hod_cos', 'radius500m_inflow_lag1', 'radius100m_inflow_rollmean12', 'dow_cos', 'radius100m_inflow_lag1', 'radius100m_outflow_lag1', 'radius500m_outflow_lag1', 'radius200m_outflow_lag1', 'temp', 'radius500m_outflow_lag12', 'dow', 'radius500m_outflow_rollmean6']

In [35]:
# ==========================================
# 1. SETUP & TARGET CHANGE
# ==========================================
from pyspark.ml.regression import GBTRegressor # Need to import GBT

targetStation = "STN_0004" 
target_col = "station_inflow" # Changed to Inflow

# Ensure gold_df is loaded beforehand, then filter to the target station
gold_df_stn = gold_df.filter(F.col("station_id") == targetStation)

# Time bounds (Train < Aug 1st, Test >= Aug 1st)
test_date = "2025-08-01 00:00:00"
validation_date = "2025-07-01 00:00:00" # Carving out July for tuning

# Create splits
train_full_df = gold_df_stn.filter(F.col("ts_hour") < test_date).cache()
test_df = gold_df_stn.filter(F.col("ts_hour") >= test_date).cache()

# Splitting train further for tuning
tune_train_df = train_full_df.filter(F.col("ts_hour") < validation_date).cache()
tune_val_df = train_full_df.filter(F.col("ts_hour") >= validation_date).cache()

print(f"Data Ready!")
print(f"Total Training Pool (< Aug): {train_full_df.count():,} rows")
print(f"Testing Data (>= Aug): {test_df.count():,} rows")

# ==========================================
# 2. FEATURE SELECTION (INFLOW)
# ==========================================
TOP_15_INFLOW_COLS = [
    "radius200m_inflow_lag1", 
    "radius100m_inflow_rollmean6", 
    "hod", 
    "hod_cos", 
    "radius500m_inflow_lag1", 
    "radius100m_inflow_rollmean12", 
    "dow_cos", 
    "radius100m_inflow_lag1", 
    "radius100m_outflow_lag1",
    "radius500m_outflow_lag1", 
    "radius200m_outflow_lag1",
    "temp", 
    "radius500m_outflow_lag12", 
    "dow", 
    "radius500m_outflow_rollmean6"
]

assembler = VectorAssembler(inputCols=TOP_15_INFLOW_COLS, outputCol="features", handleInvalid="skip")
feature_stages = [assembler]

# ==========================================
# 3. GBT ARCHITECTURE & TUNING
# ==========================================
gbt = GBTRegressor(featuresCol="features", labelCol=target_col, seed=42)

# GBTs tune differently than RFs
gbt_grid = (ParamGridBuilder()
    .addGrid(gbt.maxDepth, [4, 6])          # Depth of trees
    .addGrid(gbt.maxIter, [50, 100])        # Number of boosting rounds
    .addGrid(gbt.stepSize, [0.05, 0.1])     # Learning rate
    .build())

evaluator_rmse = RegressionEvaluator(labelCol=target_col, metricName="rmse")
evaluator_mae = RegressionEvaluator(labelCol=target_col, metricName="mae")

print(f"\n--- Tuning INFLOW GBT ---")
best_rmse = float("inf")
best_params = None

for param_map in gbt_grid:
    gbt_with_params = gbt.copy(param_map)
    pipeline = Pipeline(stages=feature_stages + [gbt_with_params])
    
    # Train/Val logic remains the same
    temp_model = pipeline.fit(tune_train_df)
    predictions = temp_model.transform(tune_val_df)
    current_rmse = evaluator_rmse.evaluate(predictions)
    
    if current_rmse < best_rmse:
        best_rmse = current_rmse
        best_params = param_map

# ==========================================
# 4. FINAL TRAINING & SAVING
# ==========================================
final_gbt = gbt.copy(best_params)
final_pipeline = Pipeline(stages=feature_stages + [final_gbt])
best_final_inflow_model = final_pipeline.fit(train_full_df)

# Evaluate on August+ Data
test_predictions = best_final_inflow_model.transform(test_df)
print(f"Test MAE: {evaluator_mae.evaluate(test_predictions):.3f}")

# Save as inflow_GBT_optimized
save_path = f"models/{targetStation}/inflow_GBT_optimized"
best_final_inflow_model.write().overwrite().save(save_path)

26/04/18 00:13:38 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:13:38 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:13:38 WARN CacheManager: Asked to cache already cached data.
26/04/18 00:13:38 WARN CacheManager: Asked to cache already cached data.

Data Ready!
Total Training Pool (< Aug): 19,304 rows
Testing Data (>= Aug): 4,417 rows

--- Tuning INFLOW GBT ---

26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1000.8 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1004.0 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1004.4 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1005.4 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1006.2 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1008.5 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1012.4 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1014.7 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1015.1 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1016.1 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1016.9 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1019.2 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1023.2 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1026.1 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1026.6 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1027.6 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1028.4 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1030.7 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1034.6 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1037.0 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1037.5 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1038.5 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1039.2 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1041.5 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1046.1 KiB
26/04/18 00:14:21 WARN DAGScheduler: Broadcasting large task binary with size 1049.1 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1049.6 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1050.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1051.0 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1052.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1055.0 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1057.3 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1057.7 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1058.7 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1059.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1061.8 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1066.4 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1069.6 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1070.1 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1071.1 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1071.8 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1074.2 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1078.8 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1081.9 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1082.4 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1083.4 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1084.2 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1086.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1091.1 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1094.2 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1094.7 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1095.7 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1096.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1098.8 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1103.3 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1106.0 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1106.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1107.5 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1108.3 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1110.6 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1114.8 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1117.7 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1118.2 KiB
26/04/18 00:14:22 WARN DAGScheduler: Broadcasting large task binary with size 1119.2 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1120.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1122.3 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1126.9 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1130.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1130.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1131.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1132.3 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1134.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1138.8 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1141.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1141.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1142.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1143.4 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1145.7 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1150.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1152.5 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1153.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1154.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1154.7 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1156.7 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1160.4 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1162.7 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1163.2 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1164.2 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1165.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1167.3 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1171.0 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1173.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1174.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1175.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1175.9 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1178.2 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1182.7 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1185.6 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1186.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1187.1 KiB
26/04/18 00:14:23 WARN DAGScheduler: Broadcasting large task binary with size 1187.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1190.1 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1193.5 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1195.7 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1196.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1197.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1197.9 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1200.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1204.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1207.7 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1208.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1209.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1209.9 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1212.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1216.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1219.5 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1220.0 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1221.0 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1221.7 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1224.1 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1228.6 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1231.3 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1231.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1232.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1233.5 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1235.6 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1239.5 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1241.7 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1242.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1243.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1243.9 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1246.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1250.8 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1253.7 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1254.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1255.2 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1255.9 KiB
26/04/18 00:14:24 WARN DAGScheduler: Broadcasting large task binary with size 1258.2 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1262.8 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1266.0 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1266.5 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1267.5 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1268.3 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1270.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1274.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1277.4 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1277.8 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1278.8 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1279.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1281.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1285.3 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1287.3 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1287.8 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1288.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1289.2 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1290.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1293.2 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1295.4 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1295.9 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1296.9 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1297.6 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1299.9 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1304.5 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1307.9 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1308.4 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1309.4 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1310.1 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1312.4 KiB
26/04/18 00:14:25 WARN DAGScheduler: Broadcasting large task binary with size 1316.8 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1000.3 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1002.6 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1006.9 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1009.3 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1009.8 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1010.8 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1011.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1013.8 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1018.2 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1021.0 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1021.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1022.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1023.2 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1025.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1029.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1032.0 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1032.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1033.5 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1034.2 KiB
26/04/18 00:14:34 WARN DAGScheduler: Broadcasting large task binary with size 1036.2 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1039.7 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1041.9 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1042.4 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1043.4 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1044.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1046.4 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1050.7 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1053.6 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1054.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1055.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1055.8 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1058.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1062.7 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1065.6 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1066.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1067.1 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1067.9 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1070.2 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1074.5 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1077.5 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1077.9 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1078.9 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1079.7 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1082.0 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1086.3 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1089.0 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1089.5 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1090.3 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1090.9 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1092.6 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1095.7 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1097.6 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1098.0 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1099.0 KiB
26/04/18 00:14:35 WARN DAGScheduler: Broadcasting large task binary with size 1099.8 KiB

Test MAE: 2.328